on:
  workflow_dispatch:
jobs:
  job1:
    name: Job One
    runs-on: ubuntu-latest
    steps:
      - name: Output Echo One
        run: echo "Step One"
      - name: Output Echo Two
        run: echo "Step Two"
  job2:
    name: Job Two
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@v1
        with:
          text: Ship it!!!!!    
          color: white
          
